# Generated by Django 4.1.6 on 2023-02-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221223_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
