# Generated by Django 4.1.6 on 2023-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
